kkmann/adoptr

R/ContinuousPrior.R, R/SmoothnessN2.R, R/TwoStageDesign.R, R/minimize.R, man/SmoothnessN2-class.Rd, man/minimize.Rd, tests/testthat/test_GQDesign.R
I implemented the smoothness term via an approximation of the second derivative (following the idea of smoothing splines)
Furthermore, I fixed the problem for the ContinuousPrior and one issue of the c2-function
=> Implemented smoothness via second derivative

R/ContinuousPrior.R, R/DataDistribution.R, R/GroupSequentialDesign.R, R/OneStageDesign.R, R/TwoStageDesign.R, R/minimize.R, man/GSDesign-class.Rd, man/OneStageDesign-class.Rd, man/TwoStageDesign-class.Rd, man/minimize.Rd, man/print.TwoStageDesignSummary.Rd, man/summary-TwoStageDesign-method.Rd, tests/testthat/test_ContinuousPrior.R, tests/testthat/test_GQDesign.R, tests/testthat/test_constraints.R, tests/testthat/test_post_processing.R
I am still working on this issue. 
Please do not check it right now.
=> Post process

R/constraints.R, man/Constraint-class.Rd, tests/testthat/test_constraints.R
v.s.
unfortunately, there is still some work to do here. I left the todos in the code. Luckily most of the stuff is not critical for 0.1, so I am just going to open the corresponding issues.
=> minor formatting, slightly expanded docs and added one missing test case

R/TwoStageDesign.R
is now non-continuous on stopping boundaries
=> plot n properly

R/TwoStageDesign.R
=> fixed x labs, changed to proper indxed x_1

R/TwoStageDesign.R
I chose a method that fits a monotonous spline iff the data are monotonous.
This should be well-suited for a small number of pivots and also showed the most convincing results to me.
=> included spline interpolation

R/TwoStageDesign.R
=> included spline interpolation (#132)

R/ContinuousPrior.R, man/ContinuousPrior-class.Rd, tests/testthat/test_ContinuousPrior.R
I added the possibility to decide wheter normalization should be checked (default "yes", in posterior "no" because of runtime) and fixed the interval bug in condition
=> Check_normalization

R/ContinuousPrior.R, tests/testthat/test_ContinuousPrior.R
I think this was a typo before - or am I wrong?
=> conditioned pdf is 0 outside interval

R/OneStageDesign.R, R/Prior.R, R/Scores.R, R/TwoStageDesign.R, R/adoptr.R, R/minimize.R, man-roxygen/plot.R, man/OneStageDesign-class.Rd, man/Prior-class.Rd, man/TwoStageDesign-class.Rd, man/adoptr.Rd, man/evaluate.Rd, man/minimize.Rd
I mentioned the vignette in docs where it makes sense and fixed some small documentation issues
=> Vignette in docs

R/AffineScoreFunction.R, R/ContinuousPrior.R, R/DataDistribution.R, R/OneStageDesign.R, R/Prior.R, R/Scores.R, R/TwoStageDesign.R, R/adoptr.R, R/constraints.R, man/AffineScore-class.Rd, man/Constraint-class.Rd, man/NormalDataDistribution-class.Rd, man/OneStageDesign-class.Rd, man/UnconditionalScore-class.Rd, man/adoptr.Rd, man/plot-TwoStageDesign-method.Rd, man/posterior.Rd, man/predictive_cdf.Rd, man/predictive_pdf.Rd
removed ToDos and included line breaks in the documentation
=> docs revise

R/CompositeScore.R, tests/testthat/test_composite.R
=> fixed bug and added test

tests/testthat/test_composite.R
=> deleted test

R/minimize.R, tests/testthat/test_ConditionalScores.R, tests/testthat/test_ContinuousPrior.R, tests/testthat/test_DataDistribution.R, tests/testthat/test_GaussLegendreIntegration.R, tests/testthat/test_GroupSequentialDesign.R, tests/testthat/test_IntegralScores.R, tests/testthat/test_OneStageDesign.R, tests/testthat/test_PointMassPrior.R, tests/testthat/test_TwoStageDesign.R, tests/testthat/test_composite.R, tests/testthat/test_constraints.R, tests/testthat/test_minimize.R, tests/testthat/test_regularizer.R, tests/testthat/test_tunable.R
Boring but necessary systematic review of **adoptr** tests; trying my best to unify notation.
=> [ready to merge] tidy tests ;)

R/minimize.R
makes output of `minimize()` readable
=> fixed optimization output

R/ConditionalPower.R
... directly uses the pivots during optimization
=> Conditional power

R/ConditionalPower.R, R/ConditionalSampleSize.R, R/ContinuousPrior.R, R/PointMassPrior.R, R/Scores.R, R/TwoStageDesign.R, R/minimize.R, R/regularization.R, R/util.R, tests/testthat/test_OneStageDesign.R, tests/testthat/test_minimize.R
1) complete overhaul of the way we compute integral scores during optimization, roughly -10% for simple point priors.
2) consider memoisation - could not notice a speedup
=> Effective integration

R/OneStageDesign.R, R/TwoStageDesign.R, R/minimize.R, tests/testthat/test_GroupSequentialDesign.R, tests/testthat/test_OneStageDesign.R, tests/testthat/test_TwoStageDesign.R, tests/testthat/test_minimize.R
* one line printing for designs instead of entire table
* fixed display ofm optimization results
=> more concise design printing; fixed printing of optimal designs

R/DataDistribution.R, man/BinomialDataDistribution-class.Rd
Hey @kkmann ,
I think you were already right and just a small additional correction was necessary
=> Fix binomial

R/TwoStageDesign.R
This pull request aims to solve issue #246
=> Fixed bug in design2str function.
